name: PluginTemplate
main: com.dumptruckman.plugintemplate.PluginTemplate
version: maven-version-number
author: dumptruckman

commands:
  pt:
    description: Main plugin command
    usage: /<command>
  ptdebug:
    description: Main plugin command
    usage: /<command>
  ptd:
    description: Main plugin command
    usage: /<command>